### ISSUE TITLE
Retain comments in code examples?

### ISSUE THREAD

**Issue by dim** [dave/rebecca#1]
Hey, would it be possible to retain the comments in the code examples, so they appear just like in godoc? Thanks!

**Comment by dave** [comment]
Ooh thanks for the suggestion. I didn't realise they were missing... I'll take a look.

**Comment by dave** [comment]
Hi @dim give it a go now... I think that's fixed it.

**Comment by dim** [comment]
Thanks, much appreciated: https://github.com/bsm/macdaddy/commit/a93c89b3cbc889c00e4ba2b7529937244f6f3c74
